-- Stint schema v1.
-- Conventions:
--   * ids are UUIDv7 TEXT, generated by clients or the server
--   * timestamps are INTEGER milliseconds since the Unix epoch (UTC)
--   * money is INTEGER minor units (cents); rates are minor units per hour
--   * synced tables carry updated_at, deleted_at (tombstone), server_seq and field_clock

CREATE TABLE app_meta (
  key   TEXT PRIMARY KEY,
  value TEXT NOT NULL
) STRICT;

CREATE TABLE sync_counter (
  id  INTEGER PRIMARY KEY CHECK (id = 1),
  seq INTEGER NOT NULL
) STRICT;
INSERT INTO sync_counter (id, seq) VALUES (1, 0);

CREATE TABLE organization (
  id          TEXT PRIMARY KEY CHECK (id = 'org'),
  name        TEXT NOT NULL,
  settings    TEXT NOT NULL DEFAULT '{}',
  logo        TEXT,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;

CREATE TABLE users (
  id                      TEXT PRIMARY KEY,
  email                   TEXT NOT NULL COLLATE NOCASE,
  name                    TEXT NOT NULL,
  role                    TEXT NOT NULL CHECK (role IN ('admin', 'manager', 'member')),
  password_hash           TEXT,
  rate                    INTEGER,
  weekly_capacity_minutes INTEGER NOT NULL DEFAULT 2400,
  color                   TEXT NOT NULL DEFAULT '#2f7d63',
  active                  INTEGER NOT NULL DEFAULT 1,
  must_change_password    INTEGER NOT NULL DEFAULT 0,
  sync_epoch              INTEGER NOT NULL DEFAULT 0,
  manager_id              TEXT REFERENCES users (id),
  created_at              INTEGER NOT NULL,
  updated_at              INTEGER NOT NULL,
  deleted_at              INTEGER,
  server_seq              INTEGER NOT NULL DEFAULT 0,
  field_clock             TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE UNIQUE INDEX users_email ON users (email);
CREATE INDEX users_seq ON users (server_seq);

CREATE TABLE clients (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  code        TEXT,
  rate        INTEGER,
  is_internal INTEGER NOT NULL DEFAULT 0,
  notes       TEXT NOT NULL DEFAULT '',
  archived_at INTEGER,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX clients_seq ON clients (server_seq);

CREATE TABLE projects (
  id               TEXT PRIMARY KEY,
  client_id        TEXT NOT NULL REFERENCES clients (id),
  parent_id        TEXT REFERENCES projects (id),
  name             TEXT NOT NULL,
  code             TEXT,
  color            TEXT NOT NULL DEFAULT '#2f7d63',
  billable_default INTEGER NOT NULL DEFAULT 1,
  rate             INTEGER,
  budget_minutes   INTEGER,
  budget_amount    INTEGER,
  visibility       TEXT NOT NULL DEFAULT 'members' CHECK (visibility IN ('members', 'everyone')),
  notes            TEXT NOT NULL DEFAULT '',
  sort_order       REAL NOT NULL DEFAULT 0,
  archived_at      INTEGER,
  created_at       INTEGER NOT NULL,
  updated_at       INTEGER NOT NULL,
  deleted_at       INTEGER,
  server_seq       INTEGER NOT NULL DEFAULT 0,
  field_clock      TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX projects_client ON projects (client_id);
CREATE INDEX projects_parent ON projects (parent_id);
CREATE INDEX projects_seq ON projects (server_seq);

CREATE TABLE project_members (
  id          TEXT PRIMARY KEY,
  project_id  TEXT NOT NULL REFERENCES projects (id),
  user_id     TEXT NOT NULL REFERENCES users (id),
  role        TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'manager')),
  rate        INTEGER,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE UNIQUE INDEX project_members_unique ON project_members (project_id, user_id);
CREATE INDEX project_members_user ON project_members (user_id);
CREATE INDEX project_members_seq ON project_members (server_seq);

CREATE TABLE tasks (
  id          TEXT PRIMARY KEY,
  project_id  TEXT NOT NULL REFERENCES projects (id),
  name        TEXT NOT NULL,
  rate        INTEGER,
  billable    INTEGER,
  sort_order  REAL NOT NULL DEFAULT 0,
  archived_at INTEGER,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX tasks_project ON tasks (project_id);
CREATE INDEX tasks_seq ON tasks (server_seq);

CREATE TABLE tags (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  color       TEXT NOT NULL DEFAULT '#6b7280',
  archived_at INTEGER,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX tags_seq ON tags (server_seq);

CREATE TABLE time_entries (
  id            TEXT PRIMARY KEY,
  user_id       TEXT NOT NULL REFERENCES users (id),
  project_id    TEXT NOT NULL REFERENCES projects (id),
  task_id       TEXT REFERENCES tasks (id),
  description   TEXT NOT NULL DEFAULT '',
  started_at    INTEGER NOT NULL,
  duration_s    INTEGER,
  entry_date    TEXT NOT NULL,
  billable      INTEGER NOT NULL DEFAULT 1,
  rate_snapshot INTEGER,
  currency      TEXT,
  source        TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('timer', 'manual', 'grid', 'import')),
  tag_ids       TEXT NOT NULL DEFAULT '[]',
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  deleted_at    INTEGER,
  server_seq    INTEGER NOT NULL DEFAULT 0,
  field_clock   TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX time_entries_user_date ON time_entries (user_id, entry_date);
CREATE INDEX time_entries_project_date ON time_entries (project_id, entry_date);
CREATE INDEX time_entries_seq ON time_entries (server_seq);

CREATE TABLE timesheets (
  id           TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users (id),
  period_start TEXT NOT NULL,
  period_end   TEXT NOT NULL,
  status       TEXT NOT NULL CHECK (status IN ('draft', 'submitted', 'approved', 'rejected')),
  submitted_at INTEGER,
  decided_by   TEXT REFERENCES users (id),
  decided_at   INTEGER,
  comment      TEXT NOT NULL DEFAULT '',
  created_at   INTEGER NOT NULL,
  updated_at   INTEGER NOT NULL,
  deleted_at   INTEGER,
  server_seq   INTEGER NOT NULL DEFAULT 0,
  field_clock  TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE UNIQUE INDEX timesheets_period ON timesheets (user_id, period_start);
CREATE INDEX timesheets_seq ON timesheets (server_seq);

CREATE TABLE favorites (
  id          TEXT PRIMARY KEY,
  user_id     TEXT NOT NULL REFERENCES users (id),
  project_id  TEXT NOT NULL REFERENCES projects (id),
  task_id     TEXT REFERENCES tasks (id),
  sort_order  REAL NOT NULL DEFAULT 0,
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL,
  deleted_at  INTEGER,
  server_seq  INTEGER NOT NULL DEFAULT 0,
  field_clock TEXT NOT NULL DEFAULT '{}'
) STRICT;
CREATE INDEX favorites_user ON favorites (user_id);
CREATE INDEX favorites_seq ON favorites (server_seq);

CREATE TABLE sessions (
  token_hash   TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users (id),
  kind         TEXT NOT NULL CHECK (kind IN ('browser', 'desktop')),
  created_at   INTEGER NOT NULL,
  last_seen_at INTEGER NOT NULL,
  expires_at   INTEGER NOT NULL,
  user_agent   TEXT NOT NULL DEFAULT '',
  ip           TEXT NOT NULL DEFAULT ''
) STRICT;
CREATE INDEX sessions_user ON sessions (user_id);

CREATE TABLE audit_log (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  at        INTEGER NOT NULL,
  actor_id  TEXT,
  action    TEXT NOT NULL,
  entity    TEXT NOT NULL,
  entity_id TEXT,
  before    TEXT,
  after     TEXT,
  reason    TEXT NOT NULL DEFAULT '',
  ip        TEXT NOT NULL DEFAULT ''
) STRICT;
CREATE INDEX audit_entity ON audit_log (entity, entity_id);
CREATE INDEX audit_at ON audit_log (at);

CREATE TABLE backup_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  at         INTEGER NOT NULL,
  path       TEXT NOT NULL,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  ok         INTEGER NOT NULL,
  error      TEXT NOT NULL DEFAULT '',
  kind       TEXT NOT NULL DEFAULT 'scheduled'
) STRICT;
