/**
 * Builds the single-file Stint Server executable with the web client embedded.
 *
 *   bun scripts/build.ts                      # this machine's platform
 *   bun scripts/build.ts --target windows-x64 # cross-compile (also linux-x64, linux-arm64, darwin-arm64, darwin-x64)
 *   bun scripts/build.ts --all
 *
 * Output: apps/server/dist/stint-server-<target>[.exe]. Build the web client first
 * (`bun run --filter @stint/web build`); this script refuses to embed a missing one.
 */
import { existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import rootPkg from "../../../package.json" with { type: "json" };

const ROOT = resolve(import.meta.dir, "..");
const WEB_DIST = resolve(ROOT, "../web/dist");
const GEN_DIR = join(ROOT, ".build");
const OUT_DIR = join(ROOT, "dist");
const ICON = resolve(ROOT, "../desktop/src-tauri/icons/icon.ico");

const TARGETS = {
  "windows-x64": { bun: "bun-windows-x64", ext: ".exe" },
  "linux-x64": { bun: "bun-linux-x64", ext: "" },
  "linux-arm64": { bun: "bun-linux-arm64", ext: "" },
  "darwin-arm64": { bun: "bun-darwin-arm64", ext: "" },
  "darwin-x64": { bun: "bun-darwin-x64", ext: "" },
} as const;
type Target = keyof typeof TARGETS;

function hostTarget(): Target {
  const os = process.platform === "win32" ? "windows" : process.platform;
  return `${os}-${process.arch}` as Target;
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const p = join(dir, name);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

/** Generates an entry module that imports every web file so `bun build --compile` embeds it. */
function writeEntry(): string {
  if (!existsSync(join(WEB_DIST, "index.html"))) {
    throw new Error(`No web build at ${WEB_DIST}. Run: bun run --filter @stint/web build`);
  }
  const files = walk(WEB_DIST).filter((f) => !f.endsWith(".map"));
  rmSync(GEN_DIR, { recursive: true, force: true });
  mkdirSync(GEN_DIR, { recursive: true });
  const lines = files.map(
    (f, i) =>
      `import f${i} from ${JSON.stringify(relative(GEN_DIR, f).replaceAll("\\", "/"))} with { type: "file" };`,
  );
  const map = files.map(
    (f, i) => `  ${JSON.stringify(`/${relative(WEB_DIST, f).replaceAll("\\", "/")}`)}: f${i},`,
  );
  const entry = join(GEN_DIR, "entry.ts");
  writeFileSync(
    entry,
    [
      "// Generated by scripts/build.ts. Do not edit.",
      ...lines,
      'import { cli } from "../src/main.ts";',
      'import { mapSource } from "../src/web/static.ts";',
      "",
      "const files: Record<string, string> = {",
      ...map,
      "};",
      "await cli(process.argv.slice(2), mapSource(files));",
      "",
    ].join("\n"),
  );
  console.log(`Embedding ${files.length} web files`);
  return entry;
}

async function build(target: Target, entry: string) {
  const t = TARGETS[target];
  const outfile = join(OUT_DIR, `stint-server-${target}${t.ext}`);
  const args = [
    "build",
    entry,
    "--compile",
    `--target=${t.bun}`,
    "--minify",
    "--sourcemap",
    "--outfile",
    outfile,
  ];
  // Icons and version info can only be stamped when building on Windows itself.
  if (target === "windows-x64" && process.platform === "win32" && existsSync(ICON)) {
    args.push(
      `--windows-icon=${ICON}`,
      "--windows-title=Stint Server",
      "--windows-publisher=Stint",
      `--windows-version=${rootPkg.version}.0`,
      "--windows-description=Stint Server — time tracking for your office",
    );
  }
  const proc = Bun.spawn(["bun", ...args], { cwd: ROOT, stdout: "inherit", stderr: "inherit" });
  if ((await proc.exited) !== 0) throw new Error(`Build failed for ${target}`);
  console.log(
    `Built ${relative(process.cwd(), outfile)} (${(statSync(outfile).size / 1024 ** 2).toFixed(1)} MB)`,
  );
}

const argv = process.argv.slice(2);
const wanted: Target[] = argv.includes("--all")
  ? (Object.keys(TARGETS) as Target[])
  : argv.includes("--target")
    ? [argv[argv.indexOf("--target") + 1] as Target]
    : [hostTarget()];
for (const t of wanted)
  if (!(t in TARGETS)) throw new Error(`Unknown target ${t}. Use one of ${Object.keys(TARGETS).join(", ")}`);
mkdirSync(OUT_DIR, { recursive: true });
const entry = writeEntry();
for (const t of wanted) await build(t, entry);
